### ISSUE TITLE
Books cannot be fired right

### ISSUE THREAD

**Issue by rvinluan** [kevinq/Zombies-Game#2]
When the player fires a book facing right, it stays still and does not move. All other directions work fine.

Steps to reproduce:
Walk up to a bookshelf, face North, and press 'a' to take a book. Face right (East) and fire the book. Observe that the book does not continue to move East as it should.

Probable cause:
The book may be colliding with itself due to its x coordinate being off by one. This may be fixed by testing that the collided object is not the one testing for collision.

**Comment by kevinq** [comment]
Is this still a problem? it looks ok on my end

**Comment by kevinq** [comment]
oops

**Comment by rvinluan** [comment]
yeah I fixed it a while ago but couldn't update github due to lack of internet. Unless you did something that broke it again, it's cool.
